// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj1dHUt4Dk3CfgsC57npKBUysOsXjKOuw',
    appId: '1:661441638035:web:aa01dc282f61e40deee766',
    messagingSenderId: '661441638035',
    projectId: 'quiz-eb402',
    authDomain: 'quiz-eb402.firebaseapp.com',
    storageBucket: 'quiz-eb402.firebasestorage.app',
    measurementId: 'G-GTQCK4QJKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdQSsy2DGNXCUkUGUloU81PuanEa0lAvs',
    appId: '1:661441638035:android:a95e3260091295a8eee766',
    messagingSenderId: '661441638035',
    projectId: 'quiz-eb402',
    storageBucket: 'quiz-eb402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjPekZUFu6EdkPqdEtv8CATCxISXQF7oU',
    appId: '1:661441638035:ios:6f250d6fe71a9e75eee766',
    messagingSenderId: '661441638035',
    projectId: 'quiz-eb402',
    storageBucket: 'quiz-eb402.firebasestorage.app',
    iosBundleId: 'com.andi.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjPekZUFu6EdkPqdEtv8CATCxISXQF7oU',
    appId: '1:661441638035:ios:3673bfe0c09ef92eeee766',
    messagingSenderId: '661441638035',
    projectId: 'quiz-eb402',
    storageBucket: 'quiz-eb402.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj1dHUt4Dk3CfgsC57npKBUysOsXjKOuw',
    appId: '1:661441638035:web:045ed04f8520119ceee766',
    messagingSenderId: '661441638035',
    projectId: 'quiz-eb402',
    authDomain: 'quiz-eb402.firebaseapp.com',
    storageBucket: 'quiz-eb402.firebasestorage.app',
    measurementId: 'G-C35PP6WZ7Z',
  );
}
